-- 易通无人柜订单相关表结构
-- 根据易通无人柜2.0开放接口文档V1.3.2-2设计（适配易通无人柜系统）

USE smart_cabinet;

-- 1. 易通无人柜事件表 (用于记录开门事件)
CREATE TABLE yt_events (
    event_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '事件ID',
    hbl_event_no VARCHAR(50) UNIQUE COMMENT '易通流水号',
    ext_event_no VARCHAR(100) COMMENT '外部事件编号',
    device_code VARCHAR(50) NOT NULL COMMENT '设备编码',
    user_id VARCHAR(100) NOT NULL COMMENT '用户ID',
    event_type ENUM('OPEN_DOOR', 'CLOSE_DOOR', 'ORDER_CREATE') DEFAULT 'OPEN_DOOR' COMMENT '事件类型',
    pay_type TINYINT DEFAULT 0 COMMENT '支付类型 0-未知，5-支付宝扫码，6-支付宝刷脸，7-微信扫码，8-微信刷脸',
    user_type TINYINT DEFAULT 1 COMMENT '用户类型 0-未知，1-用户，2-补货员',
    status TINYINT DEFAULT 1 COMMENT '事件状态 1-进行中 2-完成 3-异常',
    nonce_str VARCHAR(50) COMMENT '随机字符串',
    request_serial VARCHAR(50) COMMENT '请求序列号',
    time_stamp VARCHAR(20) COMMENT '时间戳',
    sign VARCHAR(100) COMMENT '签名',
    company_id INT COMMENT '公司ID',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_device_code (device_code),
    INDEX idx_user_id (user_id),
    INDEX idx_hbl_event_no (hbl_event_no),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜事件记录表';

-- 2. 易通无人柜订单表 (扩展原有订单表)
CREATE TABLE yt_orders (
    order_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID',
    order_code VARCHAR(50) UNIQUE NOT NULL COMMENT '订单编号',
    hbl_order_no VARCHAR(50) COMMENT '易通订单号',
    event_id BIGINT COMMENT '关联事件ID',
    device_code VARCHAR(50) NOT NULL COMMENT '设备编码',
    user_id VARCHAR(100) NOT NULL COMMENT '用户ID',
    order_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '订单金额',
    product_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '商品金额',
    promotion_amount DECIMAL(10,2) DEFAULT 0.00 COMMENT '优惠金额',
    actual_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
    order_status ENUM('PENDING', 'PAID', 'COMPLETED', 'CANCELLED', 'REFUNDED') DEFAULT 'PENDING' COMMENT '订单状态',
    pay_status ENUM('UNPAID', 'PAID', 'REFUNDING', 'REFUNDED') DEFAULT 'UNPAID' COMMENT '支付状态',
    pay_type TINYINT DEFAULT 0 COMMENT '支付类型 0-未知，5-支付宝扫码，6-支付宝刷脸，7-微信扫码，8-微信刷脸',
    third_pay_order_id VARCHAR(100) COMMENT '第三方支付订单号',
    channel_type VARCHAR(20) COMMENT '支付渠道 alipay-支付宝 wxpay-微信',
    trade_type VARCHAR(20) COMMENT 'PAY-支付 REFUND-退款',
    share_amount DECIMAL(10,2) DEFAULT 0.00 COMMENT '分账金额(单位:分)',
    trade_time VARCHAR(20) COMMENT '支付时间',
    expired_at TIMESTAMP COMMENT '订单过期时间',
    nonce_str VARCHAR(50) COMMENT '随机字符串',
    request_serial VARCHAR(50) COMMENT '请求序列号',
    time_stamp VARCHAR(20) COMMENT '时间戳',
    sign VARCHAR(100) COMMENT '签名',
    company_id INT COMMENT '公司ID',
    remark TEXT COMMENT '订单备注',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    reserved_field4 VARCHAR(255) COMMENT '预留字段4',
    reserved_field5 VARCHAR(255) COMMENT '预留字段5',
    deleted TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_order_code (order_code),
    INDEX idx_event_id (event_id),
    INDEX idx_device_code (device_code),
    INDEX idx_user_id (user_id),
    INDEX idx_order_status (order_status),
    INDEX idx_pay_status (pay_status),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (event_id) REFERENCES yt_events(event_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜订单表';

-- 3. 易通无人柜商品表 (云库商品信息)
CREATE TABLE yt_goods (
    goods_id BIGINT PRIMARY KEY COMMENT '云库商品ID',
    hbl_sku_id VARCHAR(50) COMMENT '易通SKU ID',
    barcode VARCHAR(50) COMMENT '一维条码',
    ext_sku_code VARCHAR(100) COMMENT '第三方映射CODE',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    sku VARCHAR(100) COMMENT '规格',
    description TEXT COMMENT '商品描述',
    price DECIMAL(10,2) NOT NULL COMMENT '售价',
    raw_price DECIMAL(10,2) DEFAULT 0.00 COMMENT '原价',
    cost_price DECIMAL(10,2) DEFAULT 0.00 COMMENT '成本价',
    image_url VARCHAR(500) COMMENT '商品图片URL',
    status TINYINT DEFAULT 1 COMMENT '商品状态 1-上架 2-下架',
    goods_type TINYINT DEFAULT 1 COMMENT '商品类型 1-标品 2-非标品',
    category_id BIGINT COMMENT '商品分类ID',
    brand_name VARCHAR(100) COMMENT '品牌名称',
    weight DECIMAL(8,2) COMMENT '重量(g)',
    volume DECIMAL(8,2) COMMENT '体积(ml)',
    shelf_life INT COMMENT '保质期(天)',
    storage_condition VARCHAR(100) COMMENT '储存条件',
    company_id INT COMMENT '公司ID',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    reserved_field4 VARCHAR(255) COMMENT '预留字段4',
    deleted TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_barcode (barcode),
    INDEX idx_hbl_sku_id (hbl_sku_id),
    INDEX idx_ext_sku_code (ext_sku_code),
    INDEX idx_name (name),
    INDEX idx_status (status),
    INDEX idx_goods_type (goods_type),
    INDEX idx_category_id (category_id),
    INDEX idx_company_id (company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜商品信息表';

-- 4. 易通无人柜订单商品明细表
CREATE TABLE yt_order_items (
    item_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单商品ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    order_code VARCHAR(50) NOT NULL COMMENT '订单编号',
    goods_id BIGINT NOT NULL COMMENT '云库商品ID',
    hbl_sku_id VARCHAR(50) COMMENT '易通SKU ID',
    barcode VARCHAR(50) COMMENT '商品条码',
    ext_sku_code VARCHAR(100) COMMENT '第三方映射CODE',
    goods_name VARCHAR(200) NOT NULL COMMENT '商品名称(快照)',
    goods_sku VARCHAR(100) COMMENT '商品规格(快照)',
    goods_image VARCHAR(500) COMMENT '商品图片(快照)',
    unit_price DECIMAL(10,2) NOT NULL COMMENT '商品单价(快照)',
    raw_price DECIMAL(10,2) DEFAULT 0.00 COMMENT '商品原价(快照)',
    quantity INT NOT NULL DEFAULT 1 COMMENT '购买数量',
    subtotal DECIMAL(10,2) NOT NULL COMMENT '小计金额',
    discount_amount DECIMAL(10,2) DEFAULT 0.00 COMMENT '优惠金额',
    actual_amount DECIMAL(10,2) NOT NULL COMMENT '实付金额',
    goods_status TINYINT COMMENT '商品状态 1-正常 2-非友好 10-未上架',
    recognition_status TINYINT DEFAULT 1 COMMENT '识别状态 1-正常识别 2-异常识别',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    pay_time TIMESTAMP COMMENT '订单支付时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_order_id (order_id),
    INDEX idx_order_code (order_code),
    INDEX idx_goods_id (goods_id),
    INDEX idx_hbl_sku_id (hbl_sku_id),
    INDEX idx_barcode (barcode),
    FOREIGN KEY (order_id) REFERENCES yt_orders(order_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜订单商品明细表';

-- 5. 易通无人柜设备商品关联表
CREATE TABLE yt_device_goods (
    device_goods_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
    device_code VARCHAR(50) NOT NULL COMMENT '设备编码',
    goods_id BIGINT NOT NULL COMMENT '商品ID',
    hbl_sku_id VARCHAR(50) COMMENT '易通SKU ID',
    slot_number VARCHAR(10) COMMENT '货道编号',
    stock_quantity INT DEFAULT 0 COMMENT '库存数量',
    max_capacity INT DEFAULT 0 COMMENT '最大容量',
    warning_threshold INT DEFAULT 5 COMMENT '预警阈值',
    status TINYINT DEFAULT 1 COMMENT '状态 1-上架 2-下架',
    last_refill_time TIMESTAMP COMMENT '最后补货时间',
    company_id INT COMMENT '公司ID',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_device_goods (device_code, goods_id),
    INDEX idx_device_code (device_code),
    INDEX idx_goods_id (goods_id),
    INDEX idx_status (status),
    FOREIGN KEY (goods_id) REFERENCES yt_goods(goods_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜设备商品关联表';

-- 6. 易通无人柜识别结果表
CREATE TABLE yt_recognition_results (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '识别结果ID',
    event_id BIGINT NOT NULL COMMENT '事件ID',
    hbl_event_no VARCHAR(50) COMMENT '易通无人柜流水号',
    ext_event_no VARCHAR(100) COMMENT '外部事件编号',
    device_code VARCHAR(50) NOT NULL COMMENT '设备编码',
    recog_code INT DEFAULT 0 COMMENT '识别码 0:识别中 1:正常 256:视频问题无法识别 1000:未开门/开门无订单 1001:无效订单',
    anomaly_code INT DEFAULT 0 COMMENT '异常码 0:无异常 1:未上架 2:非友好 3:未上架和非友好 99:无购物',
    video_url VARCHAR(500) COMMENT '视频地址',
    video_status INT COMMENT '视频状态 1:未上架 2:非友好 3:未上架和非友好 5:未上架和购物过多 7:未上架和非友好和购物过多',
    expires BIGINT COMMENT '过期时间(时间戳)',
    recognition_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '识别时间',
    company_id INT COMMENT '公司ID',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_event_id (event_id),
    INDEX idx_hbl_event_no (hbl_event_no),
    INDEX idx_device_code (device_code),
    INDEX idx_recog_code (recog_code),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (event_id) REFERENCES yt_events(event_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜识别结果表';

-- 7. 易通无人柜识别商品明细表
CREATE TABLE yt_recognition_items (
    item_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '识别商品ID',
    result_id BIGINT NOT NULL COMMENT '识别结果ID',
    event_id BIGINT NOT NULL COMMENT '事件ID',
    sku_id VARCHAR(50) COMMENT '易通无人柜商品ID',
    barcode VARCHAR(50) COMMENT '一维条码',
    ext_sku_code VARCHAR(100) COMMENT '第三方映射CODE',
    goods_name VARCHAR(200) COMMENT '商品名称',
    quantity INT DEFAULT 1 COMMENT '识别数量',
    goods_status TINYINT COMMENT '商品状态 1-正常 2-非友好 10-未上架',
    unit_price DECIMAL(10,2) COMMENT '商品单价',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_result_id (result_id),
    INDEX idx_event_id (event_id),
    INDEX idx_sku_id (sku_id),
    INDEX idx_barcode (barcode),
    FOREIGN KEY (result_id) REFERENCES yt_recognition_results(result_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜识别商品明细表';

-- 8. 易通无人柜分账记录表
CREATE TABLE yt_share_records (
    share_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分账ID',
    event_id BIGINT COMMENT '事件ID',
    order_id BIGINT COMMENT '订单ID',
    third_pay_order_id VARCHAR(100) COMMENT '第三方支付分账流水号',
    channel_type VARCHAR(20) COMMENT '支付渠道 alipay-支付宝 wxpay-微信',
    trade_type VARCHAR(20) COMMENT 'PAY-支付 REFUND-退款',
    order_amount DECIMAL(10,2) COMMENT '订单金额(单位:分)',
    share_amount DECIMAL(10,2) COMMENT '分账金额(单位:分)',
    trade_time VARCHAR(20) COMMENT '支付时间',
    share_status ENUM('PENDING', 'SUCCESS', 'FAILED') DEFAULT 'PENDING' COMMENT '分账状态',
    company_id INT COMMENT '公司ID',
    nonce_str VARCHAR(50) COMMENT '随机字符串',
    request_serial VARCHAR(50) COMMENT '请求序列号',
    time_stamp VARCHAR(20) COMMENT '时间戳',
    sign VARCHAR(100) COMMENT '签名',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_event_id (event_id),
    INDEX idx_order_id (order_id),
    INDEX idx_third_pay_order_id (third_pay_order_id),
    INDEX idx_share_status (share_status),
    INDEX idx_trade_time (trade_time),
    FOREIGN KEY (event_id) REFERENCES yt_events(event_id) ON DELETE SET NULL,
    FOREIGN KEY (order_id) REFERENCES yt_orders(order_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜分账记录表';

-- 9. 易通无人柜用户扩展表 (扩展原有用户信息)
CREATE TABLE yt_users (
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    original_user_id BIGINT COMMENT '关联原用户表ID',
    hbl_user_id VARCHAR(100) UNIQUE COMMENT '易通无人柜用户ID',
    openid VARCHAR(100) COMMENT '微信OpenID',
    unionid VARCHAR(100) COMMENT '微信UnionID',
    nickname VARCHAR(100) COMMENT '用户昵称',
    avatar_url VARCHAR(500) COMMENT '头像URL',
    phone VARCHAR(20) COMMENT '手机号',
    real_name VARCHAR(50) COMMENT '真实姓名',
    id_card VARCHAR(20) COMMENT '身份证号',
    gender TINYINT DEFAULT 0 COMMENT '性别 0-未知 1-男 2-女',
    birthday DATE COMMENT '生日',
    register_source VARCHAR(50) DEFAULT 'MINIPROGRAM' COMMENT '注册来源',
    last_login_time TIMESTAMP COMMENT '最后登录时间',
    login_count INT DEFAULT 0 COMMENT '登录次数',
    total_order_count INT DEFAULT 0 COMMENT '总订单数',
    total_order_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '总订单金额',
    credit_score INT DEFAULT 500 COMMENT '信用分',
    user_level TINYINT DEFAULT 1 COMMENT '用户等级',
    status TINYINT DEFAULT 1 COMMENT '用户状态 1-正常 2-禁用',
    company_id INT COMMENT '公司ID',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    reserved_field4 VARCHAR(255) COMMENT '预留字段4',
    reserved_field5 VARCHAR(255) COMMENT '预留字段5',
    deleted TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_hbl_user_id (hbl_user_id),
    INDEX idx_openid (openid),
    INDEX idx_phone (phone),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (original_user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜用户扩展表';

-- 10. 易通无人柜设备扩展表
CREATE TABLE yt_devices (
    device_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '设备ID',
    device_code VARCHAR(50) UNIQUE NOT NULL COMMENT '设备编码',
    ext_code VARCHAR(100) COMMENT '外部编码',
    device_name VARCHAR(100) COMMENT '设备名称',
    device_model VARCHAR(50) COMMENT '设备型号',
    net_status TINYINT DEFAULT 0 COMMENT '网络状态 0-未知 1-在线 2-离线',
    ele_status TINYINT DEFAULT 0 COMMENT '电源状态 0-未知 1-通电 2-断电',
    door_status TINYINT DEFAULT 0 COMMENT '门状态 0-未知 1-开门 2-关门',
    is_forbidden TINYINT DEFAULT 0 COMMENT '是否锁定 0-未锁定 1-锁定',
    location VARCHAR(255) COMMENT '设备位置',
    address VARCHAR(500) COMMENT '详细地址',
    merchant_id INT COMMENT '商户ID',
    company_id INT COMMENT '公司ID',
    last_heartbeat TIMESTAMP COMMENT '最后心跳时间',
    system_volume INT DEFAULT 50 COMMENT '系统音量(0-100)',
    media_volume INT DEFAULT 50 COMMENT '广告音量(0-100)',
    not_open_lock_delay INT DEFAULT 6 COMMENT '未开门落锁时间(秒)',
    firmware_version VARCHAR(50) COMMENT '固件版本',
    app_version VARCHAR(50) COMMENT 'APP版本',
    reserved_field1 VARCHAR(255) COMMENT '预留字段1',
    reserved_field2 VARCHAR(255) COMMENT '预留字段2',
    reserved_field3 VARCHAR(255) COMMENT '预留字段3',
    reserved_field4 VARCHAR(255) COMMENT '预留字段4',
    deleted TINYINT DEFAULT 0 COMMENT '是否删除 0-未删除 1-已删除',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_device_code (device_code),
    INDEX idx_ext_code (ext_code),
    INDEX idx_net_status (net_status),
    INDEX idx_company_id (company_id),
    INDEX idx_last_heartbeat (last_heartbeat)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='易通无人柜设备扩展表';

